skip_tags: false
image: Visual Studio 2015
platform: Any CPU
configuration: Release
services:
  - msmq
  - mysql

init:
- ps: |
    Write-Host "Installing RabbitMQ..." -ForegroundColor Cyan
    $version = '3.6.5'
    Write-Host "Downloading..."
    $exePath = "$($env:USERPROFILE)\rabbitmq-server-$($version).exe"
    (New-Object Net.WebClient).DownloadFile("http://www.rabbitmq.com/releases/rabbitmq-server/v$($version)/rabbitmq-server-$($version).exe", $exePath)
    Write-Host "Installing..."
    cmd /c start /wait $exePath /S
    $rabbitPath = "C:\Program Files (x86)\RabbitMQ Server\rabbitmq_server-$($version)"
    Write-Host "Installing service..."
    Start-Process -Wait "$rabbitPath\sbin\rabbitmq-service.bat" "install"
    Write-Host "Starting service..."
    Start-Process -Wait "$rabbitPath\sbin\rabbitmq-service.bat" "start"
    Get-Service "RabbitMQ"
    Write-Host "RabbitMQ installed and started" -ForegroundColor Green

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

build_script:
  - ps: make\make.ps1 -t build

test: off

artifacts:
  - path: reports
    name: Reports
  - path: '*.nupkg'
    name: Packages